### ISSUE TITLE
localhost:8910 says `Something went wrong.` after "successful" install

### ISSUE THREAD

**Issue by Jolg42** [redwoodjs/example-blog#24]
Node v12.14.1
macOS 10.15.3
yarn 1.21.1

`http://localhost:8910/` says `Something went wrong.`

Here is the output from my Firefox Developer 74.0b5 (64-bit) browser:

```
[HMR] Waiting for update signal from WDS... app.chunk.js:65064:12
Download the React DevTools for a better development experience: https://fb.me/react-devtools app.chunk.js:50662:17
SyntaxError: invalid regexp group app.chunk.js:2753:196
The above error occurred in the <RouterImpl> component:
    in RouterImpl (created by LocationProvider)
    in LocationProvider (created by Context.Consumer)
    in Location (created by Router)
    in Router (created by Routes)
    in Routes
    in ApolloProvider (created by GraphQLProvider)
    in GraphQLProvider (created by RedwoodProvider)
    in RedwoodProvider
    in FatalErrorBoundary

React will try to recreate this component tree from scratch using the error boundary you provided, FatalErrorBoundary. app.chunk.js:45194:13
[WDS] Hot Module Replacement enabled. app.chunk.js:64153:9
[WDS] Live Reloading enabled. app.chunk.js:64157:9
[WDS] Disconnected! app.chunk.js:64277:9
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://localhost:8910/static/js/app.chunk.js
Source Map URL: app.chunk.js.map

```

I did the setup of the project a few minutes ago with:
```
git clone https://github.com/redwoodjs/example-blog.git redwood-example-blog
cd redwood-example-blog
And following instructions from Instructions from https://github.com/redwoodjs/example-blog/#installation
```

See full output of my install here https://github.com/prisma/prisma2/issues/1819#issuecomment-597657690

**Comment by pantharshit00** [comment]
This looks like a firefox specific issue. I can reproduce this on firefox version `75.0b2`

![image](https://user-images.githubusercontent.com/22195362/76519365-da5acb00-6486-11ea-888a-4c4dd54193d3.png)


It work well on Chromium:
![image](https://user-images.githubusercontent.com/22195362/76519380-e3e43300-6486-11ea-927b-b1e2e2fe04fb.png)

**Comment by pnfcre** [comment]
Related to this issue: https://github.com/redwoodjs/redwood/issues/205

**Comment by cannikin** [comment]
We believe this is caused by https://github.com/redwoodjs/redwood/issues/205 and we're tracking a fix over there.;
