### ISSUE TITLE
Failed to compile.  ./src/Routes.js Module not found: Error: Can't resolve 'srcpagesAboutPage' in 'C:\Users\Jan\Documents\throwaway\example-blog\web\src'

### ISSUE THREAD

**Issue by janpio** [redwoodjs/example-blog#28]
I follow: https://github.com/redwoodjs/example-blog#installation

When the browser opens, I get this:

```
Failed to compile.

./src/Routes.js
Module not found: Error: Can't resolve 'srcpagesAboutPage' in 'C:\Users\Jan\Documents\throwaway\example-blog\web\src'
```

![image](https://user-images.githubusercontent.com/183673/76436760-e9734780-63b8-11ea-886e-9f01bc8b3000.png)

I am on Windows 10, thing that might be relevant because of the `srcpagesAboutPage`. Looks to me it might be using wrong directory separator that is getting removed somewhere.

**Comment by Shelob9** [comment]
I am getting the same issue. I am also on Windows 10.

I am now testing with gitpod -- https://gitpod.io/#https://github.com/redwoodjs/example-blog -- and do not see the issue.

**Comment by stefmedjo** [comment]
Same issue here also.

**Comment by cannikin** [comment]
We're looking into this and will have an update soon! It's a core Redwood issue so when that's resolved we'll update this example app as well.

**Comment by cannikin** [comment]
We're tracking this over at https://github.com/redwoodjs/redwood/issues/219

**Comment by cannikin** [comment]
We've released a couple of updates that should be helping folks on Windows. Can you try upgrading and see if this fixes it for you? See the release notes for how to upgrade: https://github.com/redwoodjs/redwood/releases/tag/v0.2.2

**Comment by padunk** [comment]
I have the same issue. Change it to 0.2.2 fixed it.
Thanks.
