### ISSUE TITLE
Default provider and url don't work out of the box

### ISSUE THREAD

**Issue by schickling** [redwoodjs/example-blog#29]
In order to follow the instructions without having to change a file, the default datasource provider should be changed to `sqlite`.

![image](https://user-images.githubusercontent.com/1567498/76517597-dcf4fa80-645d-11ea-95a0-3921d7354fa8.png)

**Comment by cannikin** [comment]
We had to put "postgreql" in there so we could deploy it live, but it seems stable enough now that I think I can change to "sqlite" and then freeze the deploys on Netlify.

**Comment by cannikin** [comment]
Closed with a898e34
