### ISSUE TITLE
Leave a message about security in the README

### ISSUE THREAD

**Issue by RobertBroersma** [redwoodjs/example-blog#32]
Hi there!

There's a part in the README about enabling authentication, but I noticed there is actually no backend checks for auth in place!

I understand that this is an example, but maybe it's a good idea to leave a note for inexperienced coders. Like you said in the tutorial: _never trust the client!_

I'd be happy to make a PR if you agree!

Cheers

**Comment by cannikin** [comment]
HA Yeah we haven't build out The Redwood Way™ for authentication yet, but it's coming soon. You're welcome to open a PR but I'm afraid it'll probably all change once our official auth helpers are released. It involves automatically making a `context` object available to your serverless functions which contains the user's auth details from whatever provider you're using (our first release will support Auth0 and Netlify Identity).

**Comment by RobertBroersma** [comment]
Can't wait for The Redwood Way, Sounds great!

I guess it won't be too much of a problem in the meantime...
