### ISSUE TITLE
Consider alternative to moment

### ISSUE THREAD

**Issue by benmccann** [redwoodjs/example-blog#35]
I'm not sure if you care about this since choice of date library is `moment` independent of demonstrating Redwood, but including `moment` really bloats the bundle size. `moment` is only used to call `fromNow`. 

Two better alternatives:
* The browser has this functionality built in with `Intl.RelativeTimeFormat`. For Safari and IE support you would need a polyfill.
* Use date-fns `formatDistanceToNow`. With date-fns, you can import just this one single function and not the whole library

**Comment by benmccann** [comment]
Actually, I looked where it's used and it's only use to call `fromNow`. If you don't need Safari and IE support you could use the browser's `Intl.RelativeTimeFormat`. For full browser support I'd recommend date-fns `formatDistanceToNow`. Either would reduce bundle size dramatically

**Comment by thedavidprice** [comment]
https://github.com/redwoodjs/example-blog/pull/47
